### ISSUE TITLE
OC-ID integration with supermarket

### ISSUE THREAD

**Issue by cmluciano** [chef/supermarket#1017] opened 2015-04-10 18:55 UTC
I opened a ticket for [OC-ID integration](https://github.com/chef/oc-id/issues/53) but wanted to also open one here in case it's in the wrong place.

**Comment by nellshamrell** [comment] 2015-04-13 18:24
Duplicate of https://github.com/chef/oc-id/issues/53

**Closed** 2015-04-13 18:25 UTC
