### ISSUE TITLE
Support for GitHub Organizations

### ISSUE THREAD

**Issue by glasschef** [chef/supermarket#1086] opened 2015-07-20 03:03 UTC
It would be great to have the ability to associate Supermarket accounts with GitHub Organizations (like individual accounts).

**Comment by nellshamrell** [comment] 2015-07-20 17:03
Hello!

Thanks for suggesting this, this is on our Q3 roadmap (adding Supermarket organizations or, as we're calling them, groups)

Closing this as a duplicate of #658

**Closed by nellshamrell** 2015-07-20 17:03 UTC
Labels: Enhancement
