### ISSUE TITLE
Document backup and restore procedures

### ISSUE THREAD

**Issue by nathenharvey** [chef/supermarket#1439] opened 2016-09-26 15:40 UTC
This request came in via [the feedback site](https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/15298707-publish-documentation-to-backup-restore-a-private).

Supermarket documentation should include the procedures required to backup and restore a Supermarket.

**Comment by robbkidd** [comment] 2016-09-26 15:42
Duplicate of #1419 😃

**Closed** 2016-09-26 15:44 UTC
