### ISSUE TITLE
/bin/supermarket server not running

### ISSUE THREAD

**Issue by dpnl87** [chef/supermarket#1003] opened 2015-03-10 10:47 UTC
If I try to follow the steps in the readme to setup a basic dev environment I can't get the chef run to succeed.

It keeps trowing:
```
==> default: Chef::Exceptions::RecipeNotFound
==> default: --------------------------------
==> default: could not find recipe _git for cookbook supermarket
```
While it did install the needed cookbooks:
```
==> default: Using git (4.1.0)
==> default: Using supermarket (3.1.0)
```

Any tips on how to get it to work?

**Comment by smith** [comment] 2015-03-11 21:32
Looks like the supermarket::vagrant recipe (https://github.com/opscode-cookbooks/supermarket/blob/f5dd720a3a56344a3474435a9432202761ea1a09/recipes/vagrant.rb) includes this, and it no longer works because there is no longer a _git recipe.

I'd either use the [advanced instructions](https://github.com/chef/supermarket#local-environment-advanced), or edit the Berksfile to point at a version of the Supermarket cookbook that still has that recipe.

The `supermarket` command, and having a dev environment that easily runs in a VM that is similar to a real deployment scenario is a good idea, but the implementation included here hasn't been well maintained or tested, so at this point it's probably best to avoid it.

**Comment by nellshamrell** [comment] 2015-03-11 21:34
Definitely use the advanced instructions, I updated those two weeks ago and confirmed that they worked on a clean VM.  I'll remove the vagrant instructions as they have not worked for some time.

**Comment by nellshamrell** [comment] 2015-03-12 16:56
README.md has been updated, closing this issue.

**Closed by nellshamrell** 2015-03-12 16:56 UTC
