### ISSUE TITLE
Chef-Server OAuth2 redirects to localhost instead of redirect_uri if you don't set `fqdn` and `host` on supermarket

### ISSUE THREAD

**Issue by eropple** [chef/supermarket#1384] opened 2016-07-22 18:33 UTC
As per discussions with @nellshamrell (who is awesome and spent some well-appreciated time helping me out, thank you again!), it appears that I've run into some gremlins in the OAuth2 workflow. This may be a dupe of an outstanding bug, but it seems as if you don't set `node['supermarket']['host']`, in addition to `node['supermarket']['fqdn']`, the Chef server gets really confused when it tries to redirect back to Supermarket to finish authentication; it tries to redirect to the value of `node['supermarket']['host']` rather than the FQDN so you hit the "invalid redirect_uri" page within `oc-id`. This works about as well as you would expect!

There's probably a deeper fix, but it might be worth just updating the blog posts, doc, etc. in the interim so other people don't step on this rake. (I noticed this only because I saw 'localhost' being stuck into my Supermarket chef-zero node and worked backwards from there. Dumb luck.)

**Comment by nellshamrell** [comment] 2016-07-25 20:27
Thanks, @eropple!  Closing this as it is a duplicate of #1232, but we will look into it!

**Closed** 2016-07-25 20:28 UTC
