### ISSUE TITLE
Foodcritic quality metric is overly critical

### ISSUE THREAD

**Issue by nathenharvey** [chef/supermarket#1401] opened 2016-08-04 20:34 UTC
The [Cookbook Passes Foodcritic](https://github.com/chef-cookbooks/cookbook-quality-metrics/blob/master/quality-metrics/qm-009-foodcritic.md) quality metric specifies that only the `metadata` and `correctness` tags should be applied.

Current configuration has the quality metric failing for any tag but excludes the following:
- FC031 - Cookbook without a metadata.rb
- FC045 - Metadata does not contain cookbook name
### TODO
- [x] Ship #1400 
- [ ] Update the foodcritic rules applied to be less critical, as described here
- [ ] Update [QM-009](https://github.com/chef-cookbooks/cookbook-quality-metrics/commits/master/quality-metrics/qm-009-foodcritic.md) to reflect the then current status of the rule.

**Comment by nellshamrell** [comment] 2016-09-12 22:07
@nathenharvey looks like that metric was altered to check for any failing foodcritic rules, not only the metadata and correctness.  Can we close this issue or is there more you would like to see?

**Comment by nathenharvey** [comment] 2016-09-13 05:28
I would like to see the Supermarket only checking for `metadata` and `correctness`.  Additionally, we should show the exact foodcritic command and foodcritic version that was used to evaluate the cookbook.

**Comment by nellshamrell** [comment] 2016-09-16 16:46
Hi @nathenharvey!  Thank you for the input :)

I am open to having it only check for metadata and correctness.  My question is how will we reconcile only checking for metadata and correctness when the [Cookbook Passes Foodcritic](https://github.com/chef-cookbooks/cookbook-quality-metrics/blob/master/quality-metrics/qm-009-foodcritic.md) rule specifically states:

"This rule checks for any failing Foodcritic rules, not only correctness or metadata."

Would welcome thoughts on this :)

**Comment by nellshamrell** [comment] 2016-09-16 16:48
Additionally, #1400 will add in the functionality to show the food critic version and tags that were run on the cookbook.  That will hopefully be merged in and deployed soon!

**Comment by robbkidd** [comment] 2016-09-16 17:26
Looking at the history of [QM-009](https://github.com/chef-cookbooks/cookbook-quality-metrics/commits/master/quality-metrics/qm-009-foodcritic.md), I _think_ what's happened is that the original metric was defined as "metadata+correctness" and a note was made that the current implementation goes beyond that. Resulting in this Issue to dial it back.

My opinion: #1400 increases information available and is thusly more valuable to get worked first.

**Comment by nathenharvey** [comment] 2016-09-19 14:01
@robbkidd your sleuthing was correct!  [QM-009's description](https://github.com/chef-cookbooks/cookbook-quality-metrics/commits/master/quality-metrics/qm-009-foodcritic.md) was updated to reflect the current implementation.

I recommend:

* Ship #1400 
* Update the foodcritic rules applied to be less critical, as described here
* Update [QM-009](https://github.com/chef-cookbooks/cookbook-quality-metrics/commits/master/quality-metrics/qm-009-foodcritic.md) to reflect the then current status of the rule.

**Comment by robbkidd** [comment] 2016-10-05 13:37
While testing #1443 with the config change this issue would require, I concluded that the following does what we want:

With the following config to only check rules tagged `correctness` or `metadata` and with 31 and 45 turned off as is our wont:
```
FIERI_FOODCRITIC_FAIL_TAGS=any
FIERI_FOODCRITIC_TAGS=metadata,correctness ~FC031 ~FC045
```

I got the expected output:
```
FC064: Ensure issues_url is set in metadata: /blahblahblah/dragons/metadata.rb:1
FC065: Ensure source_url is set in metadata: /blahblahblah/dragons/metadata.rb:1
Run with Foodcritic Version 7.0.1 with tags metadata,correctness ~FC031 ~FC045 and failure tags any
```

Showing more of my work on how to arrive at those environment variable values, Fieri's `CookbookArtifact#criticize` method

* [takes](https://github.com/chef/supermarket/blob/master/src/fieri/app/models/cookbook_artifact.rb#L43) `ENV['FIERI_FOODCRITIC_FAIL_TAGS']` as foodcritic's `-f` switch 
* [splits](https://github.com/chef/supermarket/blob/master/src/fieri/app/models/cookbook_artifact.rb#L44-L46) `ENV['FIERI_FOODCRITIC_TAGS']` on whitespace and iterates over each entry as foodcritic's `-t` switch

```
> foodcritic -t metadata,correctness -t \~FC031 -t \~FC045 -l dragons | wc -l
      35
> foodcritic -t any -t \~FC031 -t \~FC045 -l dragons | wc -l
      59
```

**Comment by nellshamrell** [comment] 2016-10-20 18:42
Sounds like we might be able to correct the foodcritic run by modifying this env variable:

FIERI_FOODCRITIC_TAGS=metadata,correctness ~FC031 ~FC045

Verifying on staging.

**Comment by nellshamrell** [comment] 2016-10-20 19:04
@nathenharvey @robbkidd can you point me to a cookbook on Supermarket that has Foodcritic failures other than the correctness and metadata ones?

**Comment by nellshamrell** [comment] 2016-10-20 19:06
Nevermind, found one https://supermarket.chef.io/cookbooks/mysql#quality

**Comment by nellshamrell** [comment] 2016-10-20 19:07
Confirmed that this works on staging.

**Comment by nellshamrell** [comment] 2016-10-20 19:13
Changed in prod data bag as well

**Comment by nellshamrell** [comment] 2016-10-20 22:58
PR submitted to the cookbook quality metrics repo https://github.com/chef-cookbooks/cookbook-quality-metrics/pull/49

**Closed** 2016-11-30 20:15 UTC
Labels: Quality Metrics, ready_for_delivery
