### ISSUE TITLE
Investigate problems with Fieri taking result input as string

### ISSUE THREAD

**Issue by loganmeetsworld** [chef/supermarket#1359] opened 2016-06-27 22:19 UTC
`NoMethodErrorcookbook_artifact.rb in criticize at line 40` shows up when a cookbook is uploaded and returns an error on results when it reads the result feedback is a string. Problem shown with cookbook on this part of the criticism in `cookbook_artifact.rb`: `[result.to_s, result.failed?]`. Error: `NoMethodError: undefined method 'failed?' for String`. Unable to criticize this cookbook (quality tab was thus left blank): https://supermarket.chef.io/cookbooks/alteryx-server#quality

**Comment by nellshamrell** [comment] 2016-06-27 23:17
So far we have been unable to replicate, let's keep monitoring this for the time being.

**Comment by robbkidd** [comment] 2016-07-01 14:31
Closing this issue in favor of #1364 "Handling PaxHeader entries in uploaded tarballs"

`NoMethodError: undefined method 'failed?' for String` is triggered when the FoodCritic command run is invalid resulting in the command's help output being returned as a string instead of an instance of FoodCritic results. This was caused by a cookbook tarball including PaxHeader entries.

**Closed** 2016-07-01 14:31 UTC
