### ISSUE TITLE
omnibus build failing on RHEL 6/CentOS 6.5 and 7 - unsafe dependency

### ISSUE THREAD

**Issue by ZedCode** [chef/supermarket#993] opened 2015-03-03 20:09 UTC
I was attempting to build the omnibus supermarket package on RHEL 6. When that failed with an unsafe dependency, I decided to try using Vagrant + VirtualBox so I could try more configurations.

I tried using the chef/centos-6.5 and chef/centos-7 Vagrantfiles, then modified them to allocate 4G of memory. Once I can `vagrant ssh` I do the following:
```
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash
echo "source ~/.profile" >> .bash_profile
source .bash_profile
rvm install 2.1.4
gem install bundler
sudo yum install git -y
mkdir sm-omnibus
git clone https://github.com/chef/omnibus-supermarket.git sm-omnibus/
cd sm-omnibus
bundle install --binstubs
sudo mkdir /opt/supermarket
sudo chown vagrant:vagrant /opt/supermarket
sudo mkdir /var/cache/omnibus
sudo chown vagrant:vagrant /var/cache/omnibus
bin/omnibus build supermarket
```

The following failure is then observed on all platforms I have attempted as well as another user who observed the same output on a bare metal install of Ubuntu 14.04:
```
[...all the stuff that is working...]
                      [HealthCheck] E | Failed!
                      [HealthCheck] E | The following libraries have unsafe or unmet dependencies:
    --> /opt/supermarket/embedded/lib/python2.7/lib-dynload/_sqlite3.so

                      [HealthCheck] E | The following binaries have unsafe or unmet dependencies:

                      [HealthCheck] E | The following libraries cannot be guaranteed to be on target systems:
    --> /usr/lib64/libsqlite3.so.0 (0x00007fddc9eed000)

                      [HealthCheck] E | The precise failures were:
    --> /opt/supermarket/embedded/lib/python2.7/lib-dynload/_sqlite3.so
    DEPENDS ON: libsqlite3.so.0
      COUNT: 1
      PROVIDED BY: /usr/lib64/libsqlite3.so.0 (0x00007fddc9eed000)
      FAILED BECAUSE: Unsafe dependency

The health check failed! Please see above for important information.


/home/vagrant/.rvm/gems/ruby-2.1.4/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/health_check.rb:273:in `run!'
  /home/vagrant/.rvm/gems/ruby-2.1.4/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/health_check.rb:144:in `run!'
  /home/vagrant/.rvm/gems/ruby-2.1.4/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/project.rb:929:in `build_me'
  /home/vagrant/.rvm/gems/ruby-2.1.4/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli.rb:69:in `build'
  /home/vagrant/.rvm/gems/ruby-2.1.4/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /home/vagrant/.rvm/gems/ruby-2.1.4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /home/vagrant/.rvm/gems/ruby-2.1.4/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /home/vagrant/.rvm/gems/ruby-2.1.4/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli/base.rb:33:in `dispatch'
  /home/vagrant/.rvm/gems/ruby-2.1.4/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /home/vagrant/.rvm/gems/ruby-2.1.4/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli.rb:41:in `execute!'
  /home/vagrant/.rvm/gems/ruby-2.1.4/bundler/gems/omnibus-51ca37c7b299/bin/omnibus:11:in `<top (required)>'
  bin/omnibus:16:in `load'
  bin/omnibus:16:in `<main>'
```
I've also tried with multiple versions of Ruby (waiting to see if there's any change in the test with 1.9.3, but I'm thinking know since the failure seems specific to the version of sqlite installed). Is there something else that needs to be done that's missing from the documentation here: https://github.com/chef/omnibus-supermarket? My goal is to simply drop the resulting rpm under /vagrant then upload it to our private cloud.

Thanks!

**Comment by smith** [comment] 2015-03-04 20:20
Supermarket doesn't have an explicit sqlite dependency. We build our packages and RHEL 5 and Ubuntu 10.04 and test on newer versions. Have never seen this problem.

Could you try ensuring that there is no libsqlite3 installed on the system when trying to build it? I'm thinking maybe the Python software might be linking to the system lib because it finds it at build time, though I'm not sure about that.

The latest alpha build we have (https://packagecloud.io/chef/stable/packages/el/6/supermarket-1.6.0_alpha.0-1.x86_64.rpm) should run on RHEL 5 and 6, though not sure about 7.

Hope that helps.

**Comment by ZedCode** [comment] 2015-03-04 20:43
Thanks!

I'm going to give these steps a try on CentOS 5 to see if I can get this to build as expected. I'll report back with success/failure.

**Comment by ZedCode** [comment] 2015-03-04 22:03
I get the same issue on CentOS 5.11:

```
                      [HealthCheck] E | Failed!
                      [HealthCheck] E | The following libraries have unsafe or unmet dependencies:
    --> /opt/supermarket/embedded/lib/python2.7/lib-dynload/_sqlite3.so

                      [HealthCheck] E | The following binaries have unsafe or unmet dependencies:

                      [HealthCheck] E | The following libraries cannot be guaranteed to be on target systems:
    --> /usr/lib64/libsqlite3.so.0 (0x00002b6573492000)

                      [HealthCheck] E | The precise failures were:
    --> /opt/supermarket/embedded/lib/python2.7/lib-dynload/_sqlite3.so
    DEPENDS ON: libsqlite3.so.0
      COUNT: 1
      PROVIDED BY: /usr/lib64/libsqlite3.so.0 (0x00002b6573492000)
      FAILED BECAUSE: Unsafe dependency

The health check failed! Please see above for important information.


/home/vagrant/.rvm/gems/ruby-2.2.0/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/health_check.rb:273:in `run!'
  /home/vagrant/.rvm/gems/ruby-2.2.0/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/health_check.rb:144:in `run!'
  /home/vagrant/.rvm/gems/ruby-2.2.0/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/project.rb:929:in `build_me'
  /home/vagrant/.rvm/gems/ruby-2.2.0/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli.rb:69:in `build'
  /home/vagrant/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /home/vagrant/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /home/vagrant/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /home/vagrant/.rvm/gems/ruby-2.2.0/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli/base.rb:33:in `dispatch'
  /home/vagrant/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /home/vagrant/.rvm/gems/ruby-2.2.0/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli.rb:41:in `execute!'
  /home/vagrant/.rvm/gems/ruby-2.2.0/bundler/gems/omnibus-51ca37c7b299/bin/omnibus:11:in `<top (required)>'
  bin/omnibus:16:in `load'
  bin/omnibus:16:in `<main>'
```
Note that to get this far I had to replace gcc 4.1 with gcc 4.4 by renaming gcc and symlinking `/usr/bin/gcc44` to /usr/bin/gcc`. I then decided to see if I could simply yum remove sqlite, however, there are a lot of RHEL packages that are dependant on sqlite...including:
```
Removing:
sqlite
sqlite
Removing
coolkey
coolkey
firstboot-tui
git
hmaccalc
man
man-pages-overrides
mkinitrd
mkinitrd
nss
nss
nss-tools
openssh
openssh-clients
openssh-server
perl-Git
policycoreutils
python-sqlite
redhat-lsb
redhat-lsb
rpm
rpm-libs
rpm-python
selinux-policy
selinux-policy-targeted
setools
sqlite-devel
sqlite-devel
sudo
svrcore
svrcore
system-config-network-tui
yum
yum-fastestmirror
yum-metadata-parser
yum-plugin-replace
yum-security
yum-updatesd
```
So...that's no good, I'd like to keep yum installed...

I have not bothered building on Ubuntu yet as for compliance reasons all of our critical infrastructure needs to be on RHEL (including Supermarket and Chef Server).

I'm certain that if I could figure out how to override this behavior it wouldn't be an issue since I can easily build on the same platform I'm targeting, I'm just not familiar enough with Omnibus to know how to do that (and the default behavior probably should be that this works).

Any other ideas on what to look into?

**Comment by schisamo** [comment] 2015-03-05 15:47
@ZedCode We have have a few alpha builds of Supermarket up on our packagecloud repo:
https://packagecloud.io/chef/stable

You should be able to set up the yum repo and just install them. If you still want to build your own packages.

**Comment by ZedCode** [comment] 2015-03-06 16:36
Thanks, I'll install from that for now. It would be great if I could package it myself with omnibus in the future. (I'll let someone from chef decide if this should stay open to investigate the root cause of the failure or not).

**Comment by cmluciano** [comment] 2015-03-24 17:31
Can this be closed?

**Comment by ZedCode** [comment] 2015-03-24 17:34
I guess that depends if anyone who maintains the omnibus package cares that it doesn't build on recent OS releases. If no one cares about getting this to build, the issue can be closed as I've been successfully using the package on packagecloud.io.

**Comment by cmluciano** [comment] 2015-03-24 17:44
@ZedCode are you using kitchen to build it

**Comment by ZedCode** [comment] 2015-03-24 22:56
@cmluciano

I'm just doing a `vagrant init` with various vagrant files (found on vagrantcloud), then doing exactly what's in my first comment. Except I'm chaining them together with `&&` instead of executing each line individually. It should be straight forward. I still have everything set up to try again so let me know if you want me to try anything.

Thanks!

**Comment by smith** [comment] 2015-03-25 13:18
Yeah I'm going to close it. I haven't been able to reproduce. It's not happening in Test Kitchen (for me anyway) or Chef's CI environment.

If somebody has a need to build their own packages and is blocked by this, please reopen and we can dig into it further. Thanks!

**Closed by smith** 2015-03-25 13:18 UTC
