### ISSUE TITLE
Feature Request: allow API call to create tool in private Supermarket

### ISSUE THREAD

**Issue by jcarapet** [chef/supermarket#1510] opened 2017-01-03 19:28 UTC
As a user, I am looking to automate inspec compliance setup as part of our build system. Ideally this would mean we can create a reference point on our private supermarket of said profile. I understand that Supermarket does not store tools/profiles as tarball artifacts and just references a remote git repo. So far the only way I can see to do this is within the UI.

Is there a way to perform a POST call to the supermarket that would set that up automatically? For our uses would be a tool POST with parameters 
- name 
- tool type
- git url 
- owner

Unsure of other steps that would be needed. Can be closed as wont fix or broken into more defined issues.

**Comment by nathenharvey** [comment] 2017-01-03 22:05
this is, essentially, a duplicate of #1166

**Comment by nathenharvey** [comment] 2017-01-03 22:06
This is something we need for the Supermarket though.  Pull requests are certainly appreciated but this is something we'll be considering as we flesh out plans for our roadmap.

**Closed** 2017-01-03 22:54 UTC
