### ISSUE TITLE
Removing collaborators doesn't trigger quality rescore

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1700] opened 2017-12-04 18:27 UTC
It seems as though when you remove a collaborator from a cookbook we don't trigger a rescore of the cookbook. I had a cookbook with 2 collaborators and I removed both, but the collaborators metric still passes when it should now fail.

**Comment by tas50** [comment] 2017-12-04 18:27
It seems as though when you remove a collaborator from a cookbook we don't trigger a rescore of the cookbook. I had a cookbook with 2 collaborators and I removed both, but the collaborators metric still passes when it should now fail.

**Comment by tas50** [comment] 2017-12-04 18:28
See https://supermarket.chef.io/cookbooks/jetty#quality

**Comment by robbkidd** [comment] 2017-12-04 19:35
Dupe of #1691

I've turned that 1691 into a roll-up issue for all the events that should trigger a quality metrics run. Closing this one as a dupe.

**Closed by robbkidd** 2017-12-04 19:35 UTC
