### ISSUE TITLE
Adding a repo to curry can't find the repo

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1121] opened 2015-09-15 02:50 UTC
In the Configure Curry page when I try to add "chef-cookbooks/yum-fedora" I receive an error stating "That repository does not exist on GitHub."

**Comment by nellshamrell** [comment] 2015-09-15 17:28
Thanks for the report!  Closing this as it is a duplicate of #1117

**Closed by nellshamrell** 2015-09-15 17:29 UTC
Labels: ready
